### ISSUE TITLE
sosoaとvocoderの双方がF0入力が必要で、input nodeが衝突してfuseに失敗する

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/vv_core_inference#17]
F0入力が可能なvocoderが誕生しました。
このvocoderとsosoa（specを出力するモデル）はどちらもF0が必要になります。

どうやらonnxのfuseは同じ入力名だった場合に衝突するらしく、vocoderとsosoa結合するときにエラーになることがわかりました。

```bash
$ bash check_contour.bash

...

hifi-gan loaded!
  File "/home/runner/work/vv_core_inference/vv_core_inference/convert.py", line 580, in <module>
    run(**vars(parser.parse_args()))
  File "/home/runner/work/vv_core_inference/vv_core_inference/convert.py", line 547, in run
    decoder_onnx = fuse(spectrogram_merged_onnx, vocoder_onnx)
  File "/home/runner/work/vv_core_inference/vv_core_inference/convert.py", line 449, in fuse
    onnx.checker.check_model(merged)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/onnx/checker.py", line 119, in check_model
    C.check_model(protobuf_string, full_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however 'f0' has been used as graph input names multiple times.
```

おそらく１つのF0入力エッジ？をこの２つのモデルに入力できる必要がありそうなのですが、どうやるかがわからずにいます･･･。

**Comment by Hiroshiba** [comment]
@Yosshi999 さん、たびたびすみません･･･。また助言などいただけないでしょうか 🙇

**Comment by Yosshi999** [comment]
fuse()内の`onnx.compose.merge_graphs` を行う部分で`inputs`引数を明示的に指定することで回避できそうですね。無指定だとそのまま両方のinputsをくっつけてしまい名前がかぶってしまうようです
同じ名前であるF0は本質的に同じものと考えて良いですか？（sosfでやっているようなF0の書き換えを行っていないですよね？）

**Comment by Yosshi999** [comment]
https://github.com/Hiroshiba/vv_core_inference/blob/822bdbf16946b702c32b48d246989270d32d9308/convert.py#L445

```py
    input_names = list(set([n.name for n in model1.graph.input] + [n.name for n in model2.graph.input]) - set(["spec"]))
    merged_graph = onnx.compose.merge_graphs(model1.graph, model2.graph, [("spec", "spec")], input_names)
```

**Comment by Hiroshiba** [comment]
@Yosshi999 

> 同じ名前であるF0は本質的に同じものと考えて良いですか？（sosfでやっているようなF0の書き換えを行っていないですよね？）

そう･･･だと思っていたのですが、すみません違うかもしれません 🙇 
torchの方のが想定している挙動で、decodeに入るf0は対数f0、vococderに入る方はHzが単位のf0でした！！
https://github.com/Hiroshiba/vv_core_inference/blob/007b5c16320f10ebf4fc10dd2f9e94ff0a504a85/vv_core_inference/make_decode_forwarder.py#L61-L77

vocoder側のf0はexp_f0みたいに名前を変えて、forwarder側でexp(f0)したものを入力する手があるかもと思いました。
（ちょっと不便ですが･･･。）

**Comment by Yosshi999** [comment]
内容が異なるなら名前を変えたほうが早いですが、make_decode_forwarderを見た感じだと、exp処理をhifiganの内部に移して同じf0として扱ったほうがいいかもしれないですね。その部分のonnx化をtorchのexportに任せることもできますし

**Comment by Hiroshiba** [comment]
@Yosshi999 
同じf0として扱うの賛成です！　expかける処理はちょっとだけ複雑なので、onnx側で隠蔽したいなぁと。
hifiganを変える手もありますし、他のネットワーク同様hifigan用のwrapperを作る手もあるかもと思いました。（hifiganだけそのまま使ってたはず）

> onnx化をtorchのexportに任せる

ここに関しては、sosoa部分（スペクトログラム作るまで）は他の話者用のモデルとマージしたい一方、hifiganは共通にしたいということがあるので、sosoa+hifiganをtorchのexportに任せるのはちょっと難しいのかもとか思いました･･･！！

**Comment by Hiroshiba** [comment]
@Yosshi999 こんな感じかな、というのを作ってみたのですが同じエラーになりました 😇 

ブランチは[これ](https://github.com/Hiroshiba/vv_core_inference/tree/F0%E3%81%8C%E3%83%80%E3%83%96%E3%81%A3%E3%81%A6graph-merge%E3%81%AB%E5%A4%B1%E6%95%97%E3%81%99%E3%82%8B%E3%81%AE%E3%82%92%E7%9B%B4%E3%81%99)で、差分は[こんな感じ](https://github.com/Hiroshiba/vv_core_inference/commit/0bf1aafc884bbd62c9ad6a4b9fb14189220722b1)です･･･。
（vocoder内でexp(f0)してdecoderに与えたいf0を１つにしつつ、`merge_graphs`に`inputs`を明示的に与えてみました。）

↓実行コード（hifiganが更新され、f0が必要なものに置き換わっています）
```bash
model_dir="model"
python convert.py \
    --yukarin_s_model_dir "$model_dir/yukarin_s" "$model_dir/yukarin_s" \
    --yukarin_sa_model_dir "$model_dir/yukarin_sa" "$model_dir/yukarin_sa" \
    --yukarin_sosoa_model_dir "$model_dir/yukarin_sosoa" "$model_dir/yukarin_sosoa" \
    --yukarin_sosf_model_dir "$model_dir/yukarin_sosf" "$model_dir/yukarin_sosf" \
    --hifigan_model_dir "$model_dir/hnhifigan" \
    --working_dir "$model_dir" \
    --speaker_id 0
```

↓ログ
```console
Traceback (most recent call last):
  File "vv_core_inference/convert.py", line 580, in <module>
    run(**vars(parser.parse_args()))
  File "vv_core_inference/convert.py", line 547, in run
    decoder_onnx = fuse(spectrogram_merged_onnx, vocoder_onnx)
  File "vv_core_inference/convert.py", line 449, in fuse
    onnx.checker.check_model(merged)
  File "vv_core_inference/.venv/lib/python3.9/site-packages/onnx/checker.py", line 119, in check_model
    C.check_model(protobuf_string, full_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however 'f0' has been used as graph input names multiple times.
```

もしよければご助言をいただけると。。。

**Comment by Yosshi999** [comment]
僕の環境では再現しませんね... Pytorchのバージョンはいくつですか？こちらは1.9.0+cpuです

**Comment by Hiroshiba** [comment]
@Yosshi999 おお、ということは成功するバージョンがあるかもですかね･･･？？
自分の環境は[Githubで管理しているrequirements.txt](https://github.com/Hiroshiba/vv_core_inference/blob/007b5c16320f10ebf4fc10dd2f9e94ff0a504a85/requirements.txt)と全く同じです。
```
torch==1.9.0
onnx==1.13.0
onnxruntime==1.13.1
```

Github Actionsの環境でも落ちてそうでした。
https://github.com/Hiroshiba/vv_core_inference/actions/runs/5032982886/jobs/9026923174

Actionsの実行コードは[こちら](https://github.com/Hiroshiba/vv_core_inference/blob/007b5c16320f10ebf4fc10dd2f9e94ff0a504a85/.github/workflows/check.yml)で、シェルスクリプトにするとこんな感じだと思います。

```bash
wget https://github.com/Hiroshiba/vv_core_inference/releases/download/0.0.1/model.zip
unzip model.zip

python -m pip install --upgrade pip
pip install -r requirements.txt

bash check_contour.bash
```

**Comment by Yosshi999** [comment]
すみません`hnhifigan`と`hifigan`を取り違えていました
hnhifiganにするとエラーがさいげんしました

**Comment by Hiroshiba** [comment]
あ、なるほどです！！　良かったのか良くなかったのか･･･ 😇

**Comment by Yosshi999** [comment]
このエラーは誤検知なので、onnxの実装を簡略化してこちらに移すことで解決できそうです
https://github.com/Yosshi999/vv_core_inference/tree/original-merger
ここに修正版をプッシュしました

**Comment by Hiroshiba** [comment]
おおお、ありがとうございます、うまくいった気がします！！！

- https://github.com/Hiroshiba/vv_core_inference/pull/18

なぜかrun.pyで最適化ログが大量に流れたので、convert.pyでの最適化レベルを1つ上げました。
いったんこれで様子見･･･！
